#############################################################################
# Makefile for building: PeersterServer
# Generated by qmake (2.01a) (Qt 4.8.7) on: Fri Dec 1 00:46:35 2017
# Project:  PeersterServer.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile PeersterServer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		controller.cpp \
		serversocket.cpp \
		friendrelation.cpp \
		ratingcalculator.cpp \
		rating.cpp moc_controller.cpp \
		moc_serversocket.cpp \
		moc_friendrelation.cpp \
		moc_ratingcalculator.cpp \
		moc_rating.cpp
OBJECTS       = main.o \
		controller.o \
		serversocket.o \
		friendrelation.o \
		ratingcalculator.o \
		rating.o \
		moc_controller.o \
		moc_serversocket.o \
		moc_friendrelation.o \
		moc_ratingcalculator.o \
		moc_rating.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		PeersterServer.pro
QMAKE_TARGET  = PeersterServer
DESTDIR       = 
TARGET        = PeersterServer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PeersterServer.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl \
		/usr/lib64/libQtNetwork.prl
	$(QMAKE) -o Makefile PeersterServer.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
/usr/lib64/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile PeersterServer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/PeersterServer1.0.0 || $(MKDIR) .tmp/PeersterServer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PeersterServer1.0.0/ && $(COPY_FILE) --parents controller.h serversocket.h friendrelation.h config.h ratingcalculator.h rating.h .tmp/PeersterServer1.0.0/ && $(COPY_FILE) --parents main.cpp controller.cpp serversocket.cpp friendrelation.cpp ratingcalculator.cpp rating.cpp .tmp/PeersterServer1.0.0/ && (cd `dirname .tmp/PeersterServer1.0.0` && $(TAR) PeersterServer1.0.0.tar PeersterServer1.0.0 && $(COMPRESS) PeersterServer1.0.0.tar) && $(MOVE) `dirname .tmp/PeersterServer1.0.0`/PeersterServer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PeersterServer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_controller.cpp moc_serversocket.cpp moc_friendrelation.cpp moc_ratingcalculator.cpp moc_rating.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_controller.cpp moc_serversocket.cpp moc_friendrelation.cpp moc_ratingcalculator.cpp moc_rating.cpp
moc_controller.cpp: config.h \
		serversocket.h \
		friendrelation.h \
		ratingcalculator.h \
		rating.h \
		controller.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) controller.h -o moc_controller.cpp

moc_serversocket.cpp: config.h \
		serversocket.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) serversocket.h -o moc_serversocket.cpp

moc_friendrelation.cpp: friendrelation.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) friendrelation.h -o moc_friendrelation.cpp

moc_ratingcalculator.cpp: friendrelation.h \
		rating.h \
		ratingcalculator.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) ratingcalculator.h -o moc_ratingcalculator.cpp

moc_rating.cpp: rating.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) rating.h -o moc_rating.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp controller.h \
		config.h \
		serversocket.h \
		friendrelation.h \
		ratingcalculator.h \
		rating.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

controller.o: controller.cpp controller.h \
		config.h \
		serversocket.h \
		friendrelation.h \
		ratingcalculator.h \
		rating.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o controller.cpp

serversocket.o: serversocket.cpp serversocket.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serversocket.o serversocket.cpp

friendrelation.o: friendrelation.cpp friendrelation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o friendrelation.o friendrelation.cpp

ratingcalculator.o: ratingcalculator.cpp ratingcalculator.h \
		friendrelation.h \
		rating.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ratingcalculator.o ratingcalculator.cpp

rating.o: rating.cpp rating.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rating.o rating.cpp

moc_controller.o: moc_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controller.o moc_controller.cpp

moc_serversocket.o: moc_serversocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serversocket.o moc_serversocket.cpp

moc_friendrelation.o: moc_friendrelation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_friendrelation.o moc_friendrelation.cpp

moc_ratingcalculator.o: moc_ratingcalculator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ratingcalculator.o moc_ratingcalculator.cpp

moc_rating.o: moc_rating.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rating.o moc_rating.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

